config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :mystores] do
    member do
      get :mystores
    end
  end
  resources :stores, only: [:index, :show, :new, :create, :destroy]
  
  resources :sales, only: [:create, :destroy]
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :store
  
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :prefecture, presence: true, length: { maximum: 50 }
  validates :city, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 255 }
  
  has_many :sales, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :stores, dependent: :destroy
  has_many :sales, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_sales = user.sales.count
    @count_stores = user.stores.count
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :require_user_logged_in #全アクションはログインが必須
  before_action :correct_user, only: [:destroy]
  
  def create
    #binding.pry
    @sale = current_user.sales.build(sale_params)
    @sale.store_id = $sale
    
    #@sale = current_user.sales.build(store_id: :$sale)
    #binding.pry
    if @sale.save
      flash[:success] = '情報を投稿しました。'
      redirect_to root_url
    else
      @sale = current_user.sales.order(id: :desc).page(params[:page])
      flash.now[:danger] = '情報の投稿に失敗しました。'
      #redirect_back(fallback_location: root_path)
      #render 'toppages/index'
      #render 'stores/create'
      redirect_to root_url
    end
  end

  def destroy
    @sale.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def sale_params
    params.require(:sale).permit(:content)
  end
  
  def correct_user
    @sale = current_user.sales.find_by(id: params[:id])
    unless @sale
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :new, :create, :destroy]
  before_action :correct_user, only: [:destroy]
  
  def index
    @stores = Store.order(id: :desc).page(params[:page]).per(25)
    #if logged_in?
      #@sale = current_user.sales.build  # form_with 用
      #@sales = current_user.sales.order(id: :desc).page(params[:page])
    #end
  end

  def show
    #@store_frm = @store.find_by(id: params[:format])
    if logged_in?
      @store = Store.find(params[:id])  # form_with 用
      @sales = @store.sales.order(id: :desc).page(params[:page])
      #@stores = current_user.stores.order(id: :desc).page(params[:page])
      @sale = current_user.sales.build  # form_with 用
      #@sales = current_user.sales.order(id: :desc).page(params[:page])
    end

  end

  def new
    @store = Store.new
  end

  def create
    @store = current_user.stores.build(store_params)
    if @store.save
      flash[:success] = '店舗を登録しました。'
      redirect_to root_path
    else
      flash.now[:danger] = '店舗の登録に失敗しました。'
      render :new
    end
  end

  def destroy
    @store.destroy
    flash[:success] = '店舗を削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private
  
  def store_params
    params.require(:store).permit(:name, :prefecture, :city, :address)
  end
  
  def correct_user
    @store = current_user.stores.find_by(id: params[:id])
    unless @store
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    #if logged_in?
     # @sale = current_user.sales.build  # form_with 用
     # @sales = current_user.sales.order(id: :desc).page(params[:page])
    #end
    #@sales = Sales.order(id: :desc).page(params[:page])
    @stores = Store.order(id: :desc).page(params[:page]).per(25)
    #@sales = Sale.order(id: :desc).page(params[:page]).per(25)
    #binding.pry
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :mystores]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @sales = @user.sales.order(id: :desc).page(params[:page])
    @mystores = @user.stores.page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
    
    def mystores
    @users = User.find(params[:id])
    @mystores = @user.stores.page(params[:page])
    binding.pry
    counts(@stores)
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/stores_helper.rb
module StoresHelper
  def current_store
    @current_store ||= Store.find_by(id: params[:format])
  end

  def store_in?
    !!current_store
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Sale information</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'お店登録', new_store_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'お店一覧', stores_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
        <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>sale information</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/sales/_sales.html.erb
<ul class="list-unstyled">
  <% sales.each do |sale| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(sale.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to sale.user.name, user_path(sale.user) %> <span class="text-muted">posted at <%= sale.created_at %></span>
        </div>
        <div>
          <p><%= sale.content %></p>
        </div>
          <div>
          <% if current_user == sale.user %>
            <%= link_to "Delete", sale, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        </div>
        
        <div class="dropdown-divider"></div>
        
      </div>
    </li>
  <% end %>
  <%= paginate sales %>
</ul>

app/views/stores/_stores.html.erb
<% if stores.any? %>
  <ul class="list-unstyled">
    <% stores.each do |store| %>
      <!-- <li class="media"> --->
        
<!--        <div class="media-body"> --->
          <div>
            <%= store.name %>
          </div>
          <div class ="row">
            <p class = "col-sm-2"><%= link_to 'store情報へ', store_path(store) %></p>
            
        <div class="offset-0","col-sm-2">
          <% if current_user == store.user %>
            <%= link_to "Delete", store, method: :delete, data: { confirm: "削除してよろしいですか？" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
          </div>
          
         </div>
            
<!--          </div>
        </div> --->
      </li>
    <% end %>
  </ul>
  <%= paginate stores %>
<% end %>

app/views/stores/create.html.erb
<h1>Store#create</h1>
<p>Find me in app/views/store/create.html.erb</p>

app/views/stores/destroy.html.erb
<h1>Store#destroy</h1>
<p>Find me in app/views/store/destroy.html.erb</p>

app/views/stores/index.html.erb
<%= render 'stores', stores: @stores %>

app/views/stores/new.html.erb
<div class="text-center">
  <h1>store</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @store, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, '店名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :prefecture, '県' %>
        <%= f.text_field :prefecture, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :city, '市' %>
        <%= f.text_field :city, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :address, 'address' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
    <%= f.submit '店舗登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/stores/show.html.1.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-sm-4">
      <%= form_with(model: @store, local: true) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-sm-8">
      <%= render 'stores/stores', stores: @store %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/stores/show.html.erb
<% if logged_in? %>
    <div class="col-sm-6">
      <h3><%= @store.name %></h3>
      <div class="offset-1"><%= @store.prefecture %><%= @store.city %><%= @store.address %></div>
    </div>
    <div class="dropdown-divider"></div>

<% $sale = @store.id %>

 
  <div class="row">
    <aside class="col-sm-4">
      <%= form_with(model: @sale, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-sm-8">
      
      <%= render 'sales/sales', sales: @sales %>
    
    </div>
  </div>
<% else %>
    <% render 'toppages/index' %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
    <ul class="list-unstyled">
    <% @stores.each do |store| %>
      <li class="media">
        <div class="media-body">
          <div>
            <%= store.name %>
          </div>
          <div>
            <p><%= link_to 'View store', store_path(store) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate @stores %>
  
  
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
      <%= link_to 'login now!', login_path, class: 'btn btn-lg btn-primary' %>
    </div>
  <ul class="list-unstyled">
    <% @stores.each do |store| %>
      <li class="media">
        <div class="media-body">
          <div>
            <%= store.name %>
          </div>
          <div>
            
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate @stores %>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/mystores.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
          <% binding.pry %>
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">コメント  <span class="badge badge-secondary"><%= @count_sales %></span></a></li>
      <li class="nav-item"><a href="<%= mystores_user_patch(@user) %>" class="nav-link <%= 'active' if current_page?(mystores_user_path(@user)) %>">登録店舗  <span class="badge badge-secondary"><%= @count_stores %></span></a></li>
      
    </ul>
    <%= render 'stores/stores', users: @stores %>
    
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.1.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">コメント  <span class="badge badge-secondary"><%= @count_sales %></span></a></li>
      <li class="nav-item"><a href="<%= mystores_user_path(@mystores) %>" class="nav-link <%= 'active' if current_page?(mystores_user_path(@mystores)) %>">登録店舗  <span class="badge badge-secondary"><%= @count_stores %></span></a></li>
      
    </ul>
    
<ul class="list-unstyled">
  <% @sales.each do |sale| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          <%= link_to sale.user.name, user_path(sale.user) %> <span class="text-muted">posted at <%= sale.created_at %></span>
        </div>
        <div>
          <p><%= sale.content %></p>
        </div>
          <div>
          <% if current_user == sale.user %>
            <%= link_to "Delete", sale, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        </div>
        
        <div class="dropdown-divider"></div>
        
      </div>
    </li>
  <% end %>
  <%= paginate @sales %>
</ul>
    
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link">Microposts</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followings</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followers</a></li>
    </ul>
  </div>
</div>